apiVersion: v1
kind: Pod
metadata:
  name: alpine-sample-pod-1
  annotations:
    sharedvolume.csv: "csv1"
  labels:
    app: alpine-sample
spec:
  containers:
  - name: alpine
    image: alpine:3.18
    command: ["/bin/sh", "-c", "while true; do echo Hello from Alpine; sleep 300; done"]
    resources:
      requests:
        memory: "8Mi"
        cpu: "50m"
      limits:
        memory: "16Mi"
        cpu: "100m"
  automountServiceAccountToken: false
