apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: shared-volume-controller-system
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: shared-volume-controller
    control-plane: controller-manager
spec:
  ports:
  - name: webhook-server
    port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app.kubernetes.io/name: shared-volume-controller
    control-plane: controller-manager
