apiVersion: sv.sharedvolume.io/v1alpha1
kind: SharedVolume
metadata:
  name: basic-shared-volume
  namespace: default
spec:
  capacity: "10Gi"
  accessModes:
    - ReadWriteMany
  storageClassName: "standard"
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
  annotations:
    sv.sharedvolume.io/mount: "basic-shared-volume:/data"
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-data
      mountPath: /data
  volumes:
  - name: shared-data
    persistentVolumeClaim:
      claimName: basic-shared-volume-pvc
