apiVersion: sv.sharedvolume.io/v1alpha1
kind: ClusterSharedVolume
metadata:
  name: git-sync-volume
spec:
  capacity: "5Gi"
  accessModes:
    - ReadWriteMany
  storageClassName: "standard"
  source:
    git:
      repository: "https://github.com/example/config-repo.git"
      branch: "main"
      path: "/configs"
---
apiVersion: v1
kind: Pod
metadata:
  name: app-with-git-config
  namespace: default
  annotations:
    csv.sharedvolume.io/mount: "git-sync-volume:/app/config"
spec:
  automountServiceAccountToken: false
  containers:
  - name: app
    image: nginx:1.21
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
        ephemeral-storage: "1Gi"
      limits:
        memory: "128Mi"
        cpu: "500m"
        ephemeral-storage: "2Gi"
    ports:
    - containerPort: 80
    volumeMounts:
    - name: config-volume
      mountPath: /app/config
      readOnly: true
  volumes:
  - name: config-volume
    persistentVolumeClaim:
      claimName: git-sync-volume-pvc
