apiVersion: v1
kind: Pod
metadata:
  name: auto-mount-pod
  namespace: default
  annotations:
    sv.sharedvolume.io/mount: "my-shared-volume:/data,my-logs:/var/log/app"
spec:
  automountServiceAccountToken: false
  containers:
  - name: app
    image: busybox:1.35
    resources:
      requests:
        memory: "32Mi"
        cpu: "100m"
        ephemeral-storage: "1Gi"
      limits:
        memory: "64Mi"
        cpu: "200m"
        ephemeral-storage: "2Gi"
    command:
    - /bin/sh
    - -c
    - |
      echo "Writing to shared volume..."
      echo "Hello from $(hostname)" > /data/message.txt
      echo "Logs from $(hostname)" > /var/log/app/app.log
      tail -f /var/log/app/app.log
    volumeMounts:
    - name: shared-data
      mountPath: /data
    - name: shared-logs
      mountPath: /var/log/app
  volumes:
  - name: shared-data
    persistentVolumeClaim:
      claimName: my-shared-volume-pvc
  - name: shared-logs
    persistentVolumeClaim:
      claimName: my-logs-pvc
