apiVersion: sv.sharedvolume.io/v1alpha1
kind: ClusterSharedVolume
metadata:
  name: git-no-password-csv
spec:
  mountPath: "/opt/mnt/git-basic"
  syncInterval: "1m"
  syncTimeout: "30s"
  storageClassName: "standard"
  storage:
    capacity: "2Gi"
  source:
    git:
      url: "https://github.com/bilgehannal/bringer-data.git"
      branch: "main"
---
apiVersion: sv.sharedvolume.io/v1alpha1
kind: SharedVolume
metadata:
  name: git-no-password-sv
spec:
  mountPath: "/opt/mnt/git-basic"
  syncInterval: "1m"
  syncTimeout: "30s"
  storageClassName: "standard"
  storage:
    capacity: "2Gi"
  source:
    git:
      url: "https://github.com/bilgehannal/bringer-data.git"