apiVersion: sv.sharedvolume.io/v1alpha1
kind: ClusterSharedVolume
metadata:
  name: ssuccess-git-basic-csv
spec:
  mountPath: "/opt/mnt/git-basic"
  syncInterval: "1m"
  syncTimeout: "30s"
  storageClassName: "standard"
  storage:
    capacity: "2Gi"
  source:
    git:
      url: "https://git.example.com/scm/config/deployment-configs.git"
      branch: "master"
      user: "demo.user"
      password: "***"
---
apiVersion: sv.sharedvolume.io/v1alpha1
kind: SharedVolume
metadata:
  name: success-git-basic-sv
spec:
  mountPath: "/opt/mnt/git-basic"
  syncInterval: "1m"
  syncTimeout: "30s"
  storageClassName: "standard"
  storage:
    capacity: "2Gi"
  source:
    git:
      url: "https://github.com/example/demo-project.git"
      branch: "master"
      user: "demouser"
      password: "***"