apiVersion: sv.sharedvolume.io/v1alpha1
kind: ClusterSharedVolume
metadata:
  name: git-key-secret-csv
spec:
  mountPath: "/opt/mnt/git-basic"
  syncInterval: "1m"
  syncTimeout: "30s"
  storageClassName: "standard"
  storage:
    capacity: "2Gi"
  source:
    git:
      url: "ssh://git@bitbucket.int.sahibinden.com:7999/srp/srp-chart.git"
      branch: "master"
      privateKeyFromSecret:
        name: private-key-for-git
        key: private-key
        namespace: sv-csv-test-ns-1
---
apiVersion: sv.sharedvolume.io/v1alpha1
kind: SharedVolume
metadata:
  name: git-key-secret-sv
spec:
  mountPath: "/opt/mnt/git-basic"
  syncInterval: "1m"
  syncTimeout: "30s"
  storageClassName: "standard"
  storage:
    capacity: "2Gi"
  source:
    git:
      url: "ssh://git@bitbucket.int.sahibinden.com:7999/srp/srp-chart.git"
      branch: "master"
      privateKeyFromSecret:
        name: private-key-for-git
        key: private-key