apiVersion: sv.sharedvolume.io/v1alpha1
kind: ClusterSharedVolume
metadata:
  name: git-key-secret-csv
spec:
  mountPath: "/opt/mnt/git-basic"
  syncInterval: "1m"
  syncTimeout: "30s"
  storageClassName: "standard"
  storage:
    capacity: "2Gi"
  source:
    git:
      url: "ssh://git@git.example.com:7999/demo/demo-chart.git"
      branch: "master"
      secretRef:
        name: git-key-secret
        namespace: shared-volume-controller-system
---
apiVersion: sv.sharedvolume.io/v1alpha1
kind: SharedVolume
metadata:
  name: git-key-secret-sv
spec:
  mountPath: "/opt/mnt/git-basic"
  syncInterval: "1m"
  syncTimeout: "30s"
  storageClassName: "standard"
  storage:
    capacity: "2Gi"
  source:
    git:
      url: "ssh://git@git.example.com:7999/demo/demo-chart.git"
---
apiVersion: sv.sharedvolume.io/v1alpha1
kind: SharedVolume
metadata:
  name: git-key-secret-sv
spec:
  mountPath: "/opt/mnt/git-basic"
  syncInterval: "1m"
  syncTimeout: "30s"
  storageClassName: "standard"
  storage:
    capacity: "2Gi"
  source:
    git:
      url: "ssh://git@git.example.com:7999/org/sample-chart.git"
      branch: "master"
      privateKeyFromSecret:
        name: private-key-for-git
        key: private-key