apiVersion: sv.sharedvolume.io/v1alpha1
kind: ClusterSharedVolume
metadata:
  name: s3-secret-csv
spec:
  mountPath: "/opt/mnt/s3"
  syncInterval: "60s"
  syncTimeout: "30s"
  storageClassName: "standard"
  storage:
    capacity: "2Gi"
  source:
    s3:
      bucketName: "testbucket"
      endpointUrl: "http://s3.example.com:9010"
      region: "us-east-1"
      accessKeyFromSecret:
        name: s3
        key: accessKey
        namespace: sv-csv-test-ns-1
      secretKeyFromSecret:
        name: s3
        key: secretKey
        namespace: sv-csv-test-ns-1
      path: "x"
---
apiVersion: sv.sharedvolume.io/v1alpha1
kind: SharedVolume
metadata:
  name: s3-secret-sv
spec:
  mountPath: "/opt/mnt/s3"
  syncInterval: "60s"
  syncTimeout: "30s"
  storageClassName: "standard"
  storage:
    capacity: "2Gi"
  source:
    s3:
      bucketName: "testbucket"
      endpointUrl: "http://s3.example.com:9010"
      region: "us-east-1"
      accessKeyFromSecret:
        name: s3
        key: accessKey
      secretKeyFromSecret:
        name: s3
        key: secretKey
      path: "x"