apiVersion: sv.sharedvolume.io/v1alpha1
kind: ClusterSharedVolume
metadata:
  name: http-csv
spec:
  mountPath: "/opt/mnt/http1"
  syncInterval: "1m"
  syncTimeout: "30s"
  storageClassName: "standard"
  storage:
    capacity: "1Gi"
  source:
    http:
      url: "https://github.com/distribution/distribution/blob/6affafd1f030087d88f88841bf66a8abe2bf4d24/contrib/apache/README.MD"
---
apiVersion: sv.sharedvolume.io/v1alpha1
kind: ClusterSharedVolume
metadata:
  name: http-csv-2
spec:
  mountPath: "/opt/mnt/http2"
  syncInterval: "1m"
  syncTimeout: "30s"
  storageClassName: "standard"
  storage:
    capacity: "1Gi"
  source:
    http:
      url: "https://github.com/distribution/distribution/blob/6affafd1f030087d88f88841bf66a8abe2bf4d24/contrib/apache/README.MD"
---
apiVersion: sv.sharedvolume.io/v1alpha1
kind: SharedVolume
metadata:
  name: http-sv
spec:
  mountPath: "/opt/mnt/http2"
  syncInterval: "1m"
  syncTimeout: "30s"
  storageClassName: "standard"
  storage:
    capacity: "1Gi"
  source:
    http:
      url: "https://github.com/distribution/distribution/blob/6affafd1f030087d88f88841bf66a8abe2bf4d24/contrib/apache/README.MD"